config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}

  namespace :admin do
    resources :members, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update] do
      resources :order_products, only: [:update]
    end
    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    get 'members/my_page' => 'members#show'
    get 'members/edit' => 'members#edit'
    patch 'members' => 'members#update'
    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]

    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'

    resources :cart_products, only: [:index, :create, :destroy, :update]

    resources :addresses, except: [:show, :new]

    resources :products, only: [:index, :show]

    get 'about' => 'homes#about'
    root to: 'homes#top'
  end
    devise_for :members, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member, optional: true
  def address_all
   "〒" + self.postal_code + " " + self.address + " " + self.name
  end
   validates :name, :address, :postal_code, presence: true 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :member, optional: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, {presence: true}
  attachment :image
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :email, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {クレジットカード: 0, 銀行振込: 1 }
  enum order_status: {入金待ち:0,入金確認:1,製作中:2, 発送準備中:3,発送済み:4}
  belongs_to :member, optional: true
  has_many :order_products, dependent: :destroy
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  enum making_status:{ 製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_producs, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  attachment :image

  validates :name, {presence: true}
  validates :description, {presence: true}
  validates :price, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!

 def index
  @genres = Genre.all
  @genre = Genre.new
 end

 def create
  @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_error] = "ジャンル名を入力してください"
    redirect_to
    end
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice_update] = "ジャンル情報を更新しました"
    else
      render 'edit'
    end
 end
 private

  def genre_params
    params.require(:genre).permit(:name, :created_at, :updated_at, :image)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!

 def top
  @orders = Order.page(params[:page]).per(10).order('updated_at DESC')
 end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
 before_action :authenticate_admin!

 def index
  @members = Member.page(params[:page]).per(10)
 end

 def show
  @member = Member.find(params[:id])
 end

 def edit
  @member = Member.find(params[:id])
 end

 def update
  @member = Member.find(params[:id])
   if @member.update(member_params)
      flash[:success] = "会員情報を変更しました"
      redirect_to admin_member_path
   else
    render "edit"
   end
 end

 private
 	def member_params
 	  params.require(:member).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:adress,:phone_number,:email,:is_deleted)
 	end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 before_action :authenticate_admin!

 def show
  @order = Order.find(params[:id])
  @order_products = @order.order_products
  @sum = 0
 end

 def update
  @order = Order.find(params[:id])
  if @order.update(order_params)
   flash[:success] = "注文ステータスを変更しました"
   if @order.order_status == "入金確認"
    order_products = @order.order_products
    order_products.each do |order_product|
     order_product.making_status = "製作待ち"
     order_product.save
    end
   end
   redirect_to admin_order_path(@order)
  else
     render "show"
  end
 end

 private
	def order_params
	 params.require(:order).permit(:order_status)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def require_login
    unless current_user
        redirect_to new_admins_session_path, notice: 'Please sign in to get started!'
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_products_helper.rb
module Admin::OrderProductsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-8 offset-md-1">
    <h2>ジャンル編集</h2>
    <%= form_with model:@genre,url:admin_genre_path, local:true do |f| %>
     <div class="form-group">
      <%= f.label :ジャンル名　 %>
      <%= f.text_field :name %>
      <%= f.attachment_field :image %>
      <%= f.submit '変更を保存', class: "btn btn-success" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container t-5'>
    <div class='row'>
      <div class="col-sm-12 px-5 px-sm-0">
      <h2 class="mt-5 mb-3">ジャンル追加</h2>
      <%= form_with model:@genre, url:'/admin/genres', local:true do |f| %>
         <%= f.label :ジャンル名　 %>
         <%= f.text_field :name %>
         <%= f.attachment_field :image, class:'px-3'%>
         <%= f.submit '新規登録', class: "btn btn-primary" %>
        <% end %>
      <h2 class="mt-5 mb-3">ジャンル一覧</h2>
      <div class="d-flex flex-wrap mt-5">
      <% @genres.each do |genre| %>
        <div class="col-3 px-2 mb-4">
          <%= attachment_image_tag genre, :image, :fill, 180, 180, format: 'jpeg' %>
          <p class='font-weight-bold text-dark mt-2 mb-2' style='font-size: 20px;'><%= genre.name %></p>
          <%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h2 class="mt-5"><%= @member.last_name %><%= @member.first_name %>さんの会員詳細編集</h2>
        <%= form_with model: [:admin, @member], local: true do |f| %>
        <table class="table">
        <tr><th>会員ID</th><th><%= @member.id %></th></tr>
          <div class="form-group">
            <tr>
              <th>氏名</th>
              <th><%= f.text_field :last_name %></th>
              <th><%= f.text_field :first_name %></th>
            </tr>
          </div>
          <div class="form-group">
            <tr>
              <th>フリガナ</th>
              <th><%= f.text_field :kana_last_name %></th>
              <th><%= f.text_field :kana_first_name %></th>
            </tr>
          </div>


          <div class="form-group">
            <tr>
              <th>郵便番号</th>
              <th><%= f.text_field :postal_code %></th>
            </tr>
          </div>

          <div class="form-group">
            <tr>
              <th>住所</th>
              <th><%= f.text_field :address %></th>
            </tr>
          </div>

          <div class="form-group">
            <tr>
              <th>電話番号</th>
              <th><%= f.text_field :phone_number %></th>
            </tr>
          </div>

          <div class="form-group">
            <tr>
              <th>メールアドレス</th>
              <th><%= f.text_field :email %></th>
            </tr>
          </div>

          <div class="form-group">
            <tr>
              <th>会員ステータス</th>
              <th>
                <div class="field">
                  <%= f.radio_button :is_deleted, 'false' %>
                  <%= f.label :有効 %>
                  <%= f.radio_button :is_deleted, 'true' %>
                  <%= f.label :退会 %>
                </div>
              </th>
            </tr>
          </div>
      </table>
        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class='container'>
  <div class='row'>
    <h4 class="mt-5">　会員一覧　</h4>
    <table class="table">

      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @members.each do |member| %>
        <tr>
          <th><%= member.id %></th>
          <td>
            <%= link_to (member.last_name + member.first_name), admin_member_path(member), class: "member_#{member.id}" %>
          </td>
          <td><%= member.email %></td>
          <td>
            <% if member.is_deleted %>
              <div>退会</div>
            <% else %>
              <div>有効</div>
            <% end %>
          </td>
        </tr>
        <% end %>
        <%= paginate @members %>
      </tbody>
    </table>

    </div>
  </div>
</div>
<!--挙動の確認まだできていません！-->

app/views/admin/members/show.html.erb
<div class="container mb-5">
  <div class="row mt-5">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1><%= @member.last_name %><%= @member.first_name %>さんの会員詳細</h1>
      <table class="table">
        <tr><th>会員ID</th><th><%= @member.id %></th></tr>
        <tr><th>氏名</th><th><%= @member.last_name %> <%= @member.first_name %></th></tr>
        <tr><th>フリガナ</th><th><%= @member.kana_last_name %> <%= @member.kana_first_name %></th></tr>
        <tr><th>郵便番号</th><th><%= @member.postal_code %></th></tr>
        <tr><th>住所</th><th><%= @member.address %></th></tr>
        <tr><th>電話番号</th><th><%= @member.phone_number %></th></tr>
        <tr><th>メールアドレス</th><th><%= @member.email %></th></tr>
        <tr><th>会員ステータス</th>
        <div>
          <% if @member.is_deleted == true%>
          <td class="text-secondary">退会</td>
          <% else %>
          <td class="text-success">有効</td>
          <% end %>
        </div>
        </tr>
      </table>
       <%= link_to "編集する", edit_admin_member_path(@member), class: "btn btn-sm btn-success" %>
       &emsp;&emsp;<%= link_to "注文履歴一覧画面を見る", admin_root_path, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/orders/_index.html.erb
<table class="table table-hover table-inverse">
  <thead class="thead-light">
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @order_products.each do |order_product| %>
    <tr>
        <td><%= order_product.product.name %></td>
        <td><%= (order_product.product.price*1.08).round.to_s(:delimited, delimiter: ',') %></td>
        <td><%= order_product.quantity %></td>
        <td><%= (order_product.product.price*1.08*order_product.quantity).round.to_s(:delimited, delimiter: ',') %></td>
        <td>
          <%= form_with model: order_product, url:admin_order_order_product_path(@order, order_product), method: :patch, local: true do | f | %>
           <%= f.select :making_status,["製作不可","製作待ち","製作中","製作完了"],checked: true %>
            <%= f.submit '更新',class: "btn btn-outline-success" %>
            <% end %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/_order.html.erb
<table class="table">
  <tbody>
    <tr>
      <td>購入者</td>
      <td>
        <%= link_to admin_member_path(@order.member_id) do %>
           <%= @order.member.last_name %> <%= @order.member.first_name %>
        <% end %>
      </td>
    </tr>
    <tr>
       <td>注文日</td>
       <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
       <td>配送先</td>
       <td>〒<%= @order.postal_code.to_s %> <%= @order.address %></td>
    </tr>
    <tr>
      <td><p>支払い方法</p></td>
      <td><p><%= @order.payment_method %></p></td>
    </tr>
    <tr>
      <td><p>注文ステータス</p></td>
      <td>
        <%= form_with model: @order, url:admin_order_path(@order.id), method: :patch, local: true do | f | %>
            <%= f.select :order_status,["入金待ち","入金確認","製作中","発送準備中","発送済み"],checked: true %>
            <%= f.submit '更新',class: "btn btn-outline-success" %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/admin/orders/_price.html.erb
<table class="table table-hover table-inverse">
<tr>
  <th>商品合計</th>
  <td><%= (@order.bill - @order.shipping_fee).round.to_s(:delimited, delimiter: ',') %>円</td>
</tr>
<tr>
  <th>送料</th>
  <td><%= @order.shipping_fee %>円</td>
</tr>
<tr>
  <th>請求金額合計</th>
  <td><%= @order.bill.round.to_s(:delimited, delimiter: ',') %>円</td>
</tr>
</table>



<!--<p>商品合計　　　<%#= @order.bill %>円 </p>-->
<!--<p>送料　　　　　<%#= @order.shipping_fee %>円</p>-->
<!--<p>請求金額合計　<%#= @order.bill.to_i + @order.shipping_fee.to_i %>円</p>-->

app/views/admin/orders/show.html.erb
<%= flash[:success] %>
<div class="container">
  <div class="row mt-5">
    <div class="col-md-8 offset-md-1">
      <h2>注文履歴詳細</h2>
      <%= render "order" %>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-8">
        <%= render "index" %>
      </div>
      <div class="col-4">
        <%= render "price" %>
      </div>
    </div>
  </div>
</div>