config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}

  namespace :admin do
    resources :members, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update] do
      resources :order_products, only: [:update]
    end
    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    get 'members/my_page' => 'members#show'
    get 'members/edit' => 'members#edit'
    patch 'members' => 'members#update'
    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]

    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'

    resources :cart_products, only: [:index, :create, :destroy, :update]

    resources :addresses, except: [:show, :new]

    resources :products, only: [:index, :show]

    get 'about' => 'homes#about'
    root to: 'homes#top'
  end
    devise_for :members, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member, optional: true
  def address_all
   "〒" + self.postal_code + " " + self.address + " " + self.name
  end
   validates :name, :address, :postal_code, presence: true 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :member, optional: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, {presence: true}
  attachment :image
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :email, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {クレジットカード: 0, 銀行振込: 1 }
  enum order_status: {入金待ち:0,入金確認:1,製作中:2, 発送準備中:3,発送済み:4}
  belongs_to :member, optional: true
  has_many :order_products, dependent: :destroy
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  enum making_status:{ 製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_producs, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  attachment :image

  validates :name, {presence: true}
  validates :description, {presence: true}
  validates :price, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!

 def index
  @genres = Genre.all
  @genre = Genre.new
 end

 def create
  @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_error] = "ジャンル名を入力してください"
    redirect_to
    end
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice_update] = "ジャンル情報を更新しました"
    else
      render 'edit'
    end
 end
 private

  def genre_params
    params.require(:genre).permit(:name, :created_at, :updated_at, :image)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!

 def top
  @orders = Order.page(params[:page]).per(10).order('updated_at DESC')
 end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 before_action :authenticate_admin!

 def show
  @order = Order.find(params[:id])
  @order_products = @order.order_products
  @sum = 0
 end

 def update
  @order = Order.find(params[:id])
  if @order.update(order_params)
   flash[:success] = "注文ステータスを変更しました"
   if @order.order_status == "入金確認"
    order_products = @order.order_products
    order_products.each do |order_product|
     order_product.making_status = "製作待ち"
     order_product.save
    end
   end
   redirect_to admin_order_path(@order)
  else
     render "show"
  end
 end

 private
	def order_params
	 params.require(:order).permit(:order_status)
	end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
 before_action :authenticate_admin!

 def index
  @products = Product.all
 end

 def show
  @product = Product.find(params[:id])
 end

 def edit
  @product = Product.find(params[:id])
 end

 def update
  @product = Product.find(params[:id])
  if @product.update(product_params)
     redirect_to admin_product_path
  else
   flash[:error] = "入力してください"
      redirect_to 'edit'
  end
 end

 def new
  @product = Product.new
 end

 def create
  @product = Product.new(product_params)
  if @product.save
      redirect_to admin_product_path(@product)
  else
      flash[:error] = "入力してください"
      redirect_to new_admin_product_path
  end
 end

 def destroy
 end
  private

  def product_params
    params.require(:product).permit(:genre_id, :name, :description, :product_status, :image, :price, :created_at, :updated_at)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def require_login
    unless current_user
        redirect_to new_admins_session_path, notice: 'Please sign in to get started!'
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_products_helper.rb
module Admin::OrderProductsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-5">商品編集</h1>
        <%= form_with model: @product,url: admin_product_path, local:true do |f| %>
        <table>
          <tbody>
            <tr>
              <td>
                <h4>商品画像</h4>
              </td>
              <td>
                <%= f.attachment_field :image %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>商品名</h4>
              </td>
              <td>
                <%= f.text_field :name %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>商品説明</h4>
              </td>
              <td>
                <%= f.text_area :description %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>ジャンル</h4>
              </td>
              <td>
                <%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>税抜価格</h4>
              </td>
              <td>
                <%= f.text_field :price %>
              </td>
            </tr>
            <tr>
              <td>
                <h4>販売ステータス</h4>
              </td>
              <td>
                <%= f.radio_button :product_status, true %>
                <%= f.label :product_status, '販売中', value: true %>
                <%= f.radio_button :product_status, false %>
                <%= f.label :product_status, '販売停止中', value: false %>
                <%= f.submit '変更を保存' %>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/products/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10">
        <h1 class="mt-5">商品一覧&emsp;&emsp;&emsp;<%= link_to "新規登録へ" ,new_admin_product_path, class: "btn btn-primary" %></h1>
        <table class="table">
          <thead>
            <tr>
              <th>商品id</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @products.each do |product| %>
              <tr>
                  <td><%= product.id %></td>
                  <td><%= link_to product.name,admin_product_path(product)  %></td>
                  <td><%= product.price.to_s(:delimited, delimiter: ',') %>円</td>
                  <td><%= product.genre.name %></td>
                  <td>
                    <% if product.product_status == true %>
                      販売中
                    <% else %>
                      販売停止中
                    <% end %>
                  </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/admin/products/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-5">商品新規登録</h1>
        <%= form_with model: @product,url:admin_products_path, local:true do |f| %>
        <table>
          <tbody>
            <tr>
              <td><h4>商品画像</h4></td>
              <td><%= f.attachment_field :image %></td>
            </tr>
            <tr>
              <td><h4>商品名</h4></td>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><h4>商品説明</h4></td>
              <td><%= f.text_area :description %></td>
            </tr>
            <tr>
              <td><h4>ジャンル</h4></td>
              <td><%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
            </tr>
            <tr>
              <td><h4>税抜価格</h4></td>
              <td><%= f.text_field :price %></td>
            </tr>
            <tr>
              <td><h4>販売ステータス</h4></td>
              <td>
                <%= f.radio_button :product_status, '販売中' , checked: true %>
                <%= f.label :product_status, '販売中', value: true %>
                <%= f.radio_button :product_status, '販売停止中' %>
                <%= f.label :product_status, '販売停止中', value: false %>
                <%= f.submit '新規登録' %>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/products/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-5">商品詳細</h1>
        <div class ="container">
          <div class="row">
            <div class="col-md-3">
              <%= attachment_image_tag @product, :image, format: 'jpeg',size: "100x100" %>
            </div>
            <div class="col-md-8 offset-md-1">
              <p>商品名：<%= @product.name %></p>
              <p>商品説明：<%= @product.description %></p>
              <p>ジャンル：<%= @product.genre.name %></p>
              <p>税抜価格：<%= @product.price.to_s(:delimited, delimiter: ',') %>円</p>
              <p>(税込価格):<%= (@product.price*1.08).round.to_s(:delimited, delimiter: ',') %>円</p>
              <p>販売ステータス：
              <% if @product.product_status == true %>
                <%= '販売中' %>
              <% else %>
                <%= '販売停止中' %></p>
              <% end %>
              <%= link_to "編集する", edit_admin_product_path(@product) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>