config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}

  namespace :admin do
    resources :members, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update] do
      resources :order_products, only: [:update]
    end
    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    get 'members/my_page' => 'members#show'
    get 'members/edit' => 'members#edit'
    patch 'members' => 'members#update'
    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]

    delete 'cart_products/destroy_all' => 'cart_products#destroy_all'

    resources :cart_products, only: [:index, :create, :destroy, :update]

    resources :addresses, except: [:show, :new]

    resources :products, only: [:index, :show]

    get 'about' => 'homes#about'
    root to: 'homes#top'
  end
    devise_for :members, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member, optional: true
  def address_all
   "〒" + self.postal_code + " " + self.address + " " + self.name
  end
   validates :name, :address, :postal_code, presence: true 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :member, optional: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, {presence: true}
  attachment :image
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_products, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :email, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {クレジットカード: 0, 銀行振込: 1 }
  enum order_status: {入金待ち:0,入金確認:1,製作中:2, 発送準備中:3,発送済み:4}
  belongs_to :member, optional: true
  has_many :order_products, dependent: :destroy
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  enum making_status:{ 製作不可:0, 製作待ち:1, 製作中:2, 製作完了:3}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_producs, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  attachment :image

  validates :name, {presence: true}
  validates :description, {presence: true}
  validates :price, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!

 def index
  @genres = Genre.all
  @genre = Genre.new
 end

 def create
  @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash[:genre_error] = "ジャンル名を入力してください"
    redirect_to
    end
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice_update] = "ジャンル情報を更新しました"
    else
      render 'edit'
    end
 end
 private

  def genre_params
    params.require(:genre).permit(:name, :created_at, :updated_at, :image)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!

 def top
  @orders = Order.page(params[:page]).per(10).order('updated_at DESC')
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def require_login
    unless current_user
        redirect_to new_admins_session_path, notice: 'Please sign in to get started!'
    end
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Naganocake</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light header" >
    <div class="container">
      <nav class="navbar-brand navbar-left header-logo">
        <a href="/">
            <img src=<%= asset_path('logo1.png') %> width="140" height="140">
          </a>
      </nav>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
    </button>
    <div class="w-75 collapse navbar-collapse">
     <ul class="nav navbar-nav ml-auto">
      <% if member_signed_in? %>
       <li class="navbar nav-member-name text-center">
         ようこそ、<%= current_member.last_name %>さん！!
       </li>
       <li class="nav-item text-right">
         <%= link_to "マイページ", members_my_page_path, class: "fas fa-user-circle nav-link text-dark text-right" %>
       </li>
       <li class="nav-item">
         <%= link_to "商品一覧", products_path, class: "fas fa-cheese nav-link text-dark text-right" %>
       </li>
       <li class="nav-item">
         <%= link_to "カート", cart_products_path,class: "fas fa-shopping-cart nav-link text-dark text-right" %>
       </li>
       <li class="nav-item">
         <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-dark text-right" %>
       </li>

      <%elsif admin_signed_in? %>
       <li class="nav-item">
         <%= link_to "商品一覧", admin_products_path, class: "fas fa-cheese nav-link text-dark text-right" %>
       </li>
       <li class="nav-item">
         <%= link_to "会員一覧", admin_members_path, class: "fas fa-users nav-link text-dark text-right"  %>
       </li>
       <li class="nav-item">
         <%= link_to "注文履歴一覧", admin_root_path, class: "fas fa-history nav-link text-dark text-right" %>
       </li>
       <li class="nav-item">
         <%= link_to "ジャンル一覧", admin_genres_path, class: "fas fa-tags nav-link text-dark text-right" %>
       </li>
       <li class="nav-item">
         <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-dark text-right" %>
       </li>

      <% else %>
       <li class="nav-item">
         <%= link_to "About", about_path, class: "fas fa-link nav-link text-dark" %>
       </li>
       <li class="nav-item">
         <%= link_to "商品一覧", products_path, class: "fas fa-cheese nav-link text-dark" %>
       </li>
       <li class="nav-item">
         <%= link_to "新規登録", new_member_registration_path, class: "fas fa-user-plus nav-link text-darkt" %>
       </li>
       <li class="nav-item">
         <%= link_to "ログイン", new_member_session_path, class: "fas fa-sign-in-alt nav-link text-dark" %>
       </li>
      <% end %>
     </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= favicon_link_tag('favicon1.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <!--<div id="container">-->
  <!--  <div id="images">-->
  <!--    <div class="image1"></div>-->
  <!--    <div class="image2"></div>-->
  <!--    <div class="image3"></div>-->
  <!--    <div class="image4"></div>-->
  <!--    <div class="image5"></div>-->
  <!--  </div>-->
  <!--</div>-->


  <body class="bg-light">
    <%= render "layouts/header" %>
    <%= yield %>
   <%= render 'layouts/footer' %>
  </body>

</html>